# Generated by Django 3.0.7 on 2020-06-17 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200617_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/photos'),
            preserve_default=False,
        ),
    ]
