# Generated by Django 3.0.7 on 2020-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='Description',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='street',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to='../../static/photos'),
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.ManyToManyField(related_name='cities', to='events.City'),
        ),
    ]
