# Generated by Django 3.0.7 on 2020-07-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200711_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutry', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='events.Country'),
        ),
    ]
