# Generated by Django 3.0.7 on 2020-07-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200711_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='coutry',
            new_name='country',
        ),
    ]
