# Generated by Django 3.0.7 on 2020-07-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200711_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.Country'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='events',
            name='city',
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.City'),
            preserve_default=False,
        ),
    ]
